### ISSUE TITLE
Refused to set the document's base URI to 'https://www.paypalobjects.com/'

### ISSUE THREAD

**Issue by tdias25** [raraujo91/paypal-plus-for-vue#5]
First of all, i want to thank you for your effort this is looking great.
I did all the tests in sandbox and it worked great, but as soon as i tested it with live credentials CSP( Content Security Policy) is messing everything up, do you know how to solve it?

i'm currently using this:
<meta http-equiv="Content-Security-Policy" content="script-src 'nonce-xxxx' 'strict-dynamic' ;">

the error message returned:
`ppplusdcc.min.js:32 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'nonce-xxxx' 'strict-dynamic' ". Either the 'unsafe-inline' keyword, a hash ('sha256-45C03KxjkH0Fp6zbMd6Wgl82IEA6F6KNQjNJlaUCv6M='), or a nonce ('nonce-...') is required to enable inline execution.`

**Comment by raraujo91** [comment]
Hey @tdias25, thanks for using this project. Is your PayPal email address already enabled to use PayPal Plus? I've took a look on this error and it might happen in case you're using an email address not enabled for this product in production (in sandbox it'll work normally). 

If this service is already enabled, please send me a screenshot from what's being displayed.

**Comment by tdias25** [comment]
i see, is the config of Paypal Plus the one about "bussiness account"?
 
here's what mine looks like:
![image](https://user-images.githubusercontent.com/5600287/114305252-ab5dc100-9aad-11eb-98b4-87ef9af84be1.png)

after some more changes to CSP, my error is now this:

![image](https://user-images.githubusercontent.com/5600287/114305284-ebbd3f00-9aad-11eb-842d-874c8ff10fbd.png)


this is my personal account that i only used for integration purposes, i don't think i ever enaled anything in production, you think in order to enable PayPal Plus i have to email the Paypal support or something?

**Comment by raraujo91** [comment]
@tdias25,

Your PayPal account must have a configuration for PayPal Plus enabled and by default it comes disabled. Currently I don't know if it's only enabled for Business accounts. You'll need to check with PayPal support team. Seems this is the reason why it's not working (once the first line from your DevTools console is returning a Forbidden code).
