### ISSUE TITLE
Como trato os erros de validação

### ISSUE THREAD

**Issue by piikenoo** [raraujo91/paypal-plus-for-vue#6]
Olá @raraujo91 tenho uma dúvida. 

O evento @error está tratando apenas os erros de retorno após prosseguir com checkout. Porém antes de enviar os dados o iframe do PayPal valida o formulário, tipo campos obrigatórios etc.

Tem alguma forma de tratar esses erros?

**Comment by raraujo91** [comment]
Oi @piikenoo, quase todos os campos do formulário são obrigatórios (exceto as checkboxes embaixo da seleção da parcela) e a validação dos campos é padrão da biblioteca da PayPal. Não é retornado um callback dos erros de validação de campos pela por ela, apenas os erros retornados conforme documentação ([referência de erros](https://developer.paypal.com/docs/integration/paypal-plus/mexico-brazil/test-your-integration-and-execute-the-payment/#handling-errors)). 

Nem na documentação do produto tem algo relacionado a como tratar os erros de validação (e pelo que já estudei e trabalhei com esse produto nunca houve algo assim) 🥲.

**Comment by piikenoo** [comment]
O meu problema era relacionado ao botão de continuar. Dando uma olha mais detalhada no readme vi que existe o atributo **buttonId** para controlar o estado do botão, porém quando ele está no estado inativo ele continua com a aparência de botão normal, é como se o PayPal travasse apenas os eventos ao clicar nele. Sendo assim, dá a impressão de que o formulário está com problema, pois o visual do formulário não é muito amigável.

**Comment by raraujo91** [comment]
Ah, entendi @piikenoo. É, realmente o PayPal não tem essa tratativa nativamente e a própria biblioteca/produto não possui callbacks de validação dos campos para habilitar o botão de Continuar apenas com tudo tiver preenchido (por exemplo, um onEvent). 

Também não é uma boa prática colocar um hook de input dos dados nos campos por se tratar de um produto de pagamento (acredito que pode dar algum problema legal posteriormente).

**Comment by piikenoo** [comment]
Compreendo @raraujo91. Valeu pela ajuda!
